language: python
jobs:
  include:
    - name: "Build for Python 3.8.0 Linux"
      os: linux
      dist: xenial
      python: 3.8
    - name: "Build for Python 3.8.0 Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: "pip3 install -r requirements.txt"

services:
- docker

script:
  - coverage run unit_test.py
  - docker image build -t magersaber/group30a2 .

after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov has failed to upload."
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to docker hub
  - docker push magersaber/group30a2
after_failure: echo "Build failed."

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "A2"
  env: "A2-env"
  bucket_name: "elasticbeanstalk-us-east-2-813592666721"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
