language: python
jobs:
  include:
    - name: "Build for Python 3.8.0 Linux"
      os: linux
      dist: xenial
      python: 3.8
    - name: "Build for Python 3.8.0 Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: "pip3 install -r requirements.txt"
script: 
  - coverage run unit_test.py 
after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov has failed to upload."
after_failure: echo "Build failed."

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dtest"
  env: "Dtest-env"
  bucket_name: "elasticbeanstalk:us-east-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
